[workspace]
members = ["crates/se_core", "crates/se_float"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
license = "GPL-3.0-or-later"
authors = ["rickgcn"]

[workspace.dependencies]
blake3 = "1"
cc = "1"
postcard = { version = "1", features = ["use-std"] }
serde = { version = "1", features = ["derive"] }

[profile.release]
lto = "fat"
codegen-units = 1
