[workspace]
members = ["crates/se_core", "crates/se_device", "crates/se_float", "crates/se_machine", "crates/se_runtime", "crates/se_ui"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["rickgcn"]

[workspace.dependencies]
cc = "1"
cxx = "1"
cxx-build = "1"
qt-build-utils = "0.9"
se_core = { path = "crates/se_core" }
se_device = { path = "crates/se_device" }
se_float = { path = "crates/se_float" }
se_machine = { path = "crates/se_machine" }
se_runtime = { path = "crates/se_runtime" }
vt100 = "0.16.2"
