[package]
name = "se_core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
postcard = { version = "1", features = ["use-std"] }
serde = { version = "1", features = ["derive"] }

[[bench]]
name = "decoder"
harness = false
