//! R4000-compatible 64-bit SECDED used by the CRIME memory controller.

/// Syndrome generated by each R4000 data bit, indexed from data bit zero.
const DATA_SYNDROMES: [u8; 64] = [
    0x13, 0x23, 0x43, 0x83, 0x2f, 0xf1, 0x0d, 0x07, 0xd0, 0x70, 0x4f, 0xf8, 0x61, 0x62, 0x64, 0x68,
    0x1c, 0x2c, 0x4c, 0x8c, 0x15, 0x25, 0x45, 0x85, 0x19, 0x29, 0x49, 0x89, 0x1a, 0x2a, 0x4a, 0x8a,
    0x51, 0x52, 0x54, 0x58, 0x91, 0x92, 0x94, 0x98, 0xa1, 0xa2, 0xa4, 0xa8, 0x31, 0x32, 0x34, 0x38,
    0x16, 0x26, 0x46, 0x86, 0x1f, 0xf2, 0x0b, 0x0e, 0xb0, 0xe0, 0x8f, 0xf4, 0xc1, 0xc2, 0xc4, 0xc8,
];

/// Result of checking one data lane and its stored ECC byte.
#[derive(Clone, Copy, Debug, Eq, PartialEq, serde::Deserialize, serde::Serialize)]
pub enum EccCheck {
    /// Data and ECC are consistent.
    Clean {
        /// Regenerated check byte.
        check: u8,
    },

    /// A single data or check bit was corrected.
    Corrected {
        /// Corrected data.
        data: u64,

        /// Observed syndrome.
        syndrome: u8,

        /// Regenerated check byte before correction.
        check: u8,
    },

    /// The syndrome cannot identify a single bit.
    Uncorrectable {
        /// Observed syndrome.
        syndrome: u8,

        /// Regenerated check byte.
        check: u8,
    },
}

/// Generates the R4000 even-parity check byte for one data doubleword.
pub fn generate(data: u64) -> u8 {
    let mut check = 0;
    let mut remaining = data;
    while remaining != 0 {
        let bit = remaining.trailing_zeros() as usize;
        check ^= DATA_SYNDROMES[bit];
        remaining &= remaining - 1;
    }
    check
}

/// Checks and, when possible, corrects one data doubleword.
pub fn check(data: u64, stored_check: u8) -> EccCheck {
    let generated = generate(data);
    let syndrome = stored_check ^ generated;
    if syndrome == 0 {
        return EccCheck::Clean { check: generated };
    }
    if syndrome.is_power_of_two() {
        return EccCheck::Corrected {
            data,
            syndrome,
            check: generated,
        };
    }
    if let Some(bit) = DATA_SYNDROMES
        .iter()
        .position(|candidate| *candidate == syndrome)
    {
        return EccCheck::Corrected {
            data: data ^ (1_u64 << bit),
            syndrome,
            check: generated,
        };
    }
    EccCheck::Uncorrectable {
        syndrome,
        check: generated,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn published_r4000_examples_generate_exact_check_values() {
        assert_eq!(generate(0), 0);
        assert_eq!(generate(1), 0x13);
        assert_eq!(generate(0x43), 0x3d);
    }

    #[test]
    fn every_single_data_bit_is_corrected() {
        let original = 0x0123_4567_89ab_cdef;
        let stored = generate(original);
        for (bit, syndrome) in DATA_SYNDROMES.into_iter().enumerate() {
            assert_eq!(
                check(original ^ (1_u64 << bit), stored),
                EccCheck::Corrected {
                    data: original,
                    syndrome,
                    check: generate(original ^ (1_u64 << bit)),
                }
            );
        }
    }

    #[test]
    fn every_single_check_bit_preserves_data() {
        let data = 0xfedc_ba98_7654_3210;
        let stored = generate(data);
        for bit in 0..8 {
            assert_eq!(
                check(data, stored ^ (1 << bit)),
                EccCheck::Corrected {
                    data,
                    syndrome: 1 << bit,
                    check: stored,
                }
            );
        }
    }

    #[test]
    fn double_data_error_is_not_corrected() {
        let data = 0;
        assert!(matches!(
            check(data ^ 0b11, generate(data)),
            EccCheck::Uncorrectable { .. }
        ));
    }
}
