[package]
name = "se_runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
se_core.workspace = true
se_machine.workspace = true

[dev-dependencies]
se_device.workspace = true
se_float.workspace = true
