[package]
name = "se_ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
cxx.workspace = true
se_cpu.workspace = true
se_machine.workspace = true
se_runtime.workspace = true

[build-dependencies]
cxx-build.workspace = true
qt-build-utils.workspace = true
