[package]
name = "se_ui"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "sgi-emu"
path = "src/main.rs"

[dependencies]
cxx.workspace = true
se_core.workspace = true
se_machine.workspace = true
se_runtime.workspace = true
vt100.workspace = true

[build-dependencies]
cxx-build.workspace = true
qt-build-utils.workspace = true
